### ISSUE TITLE
There is no samples with task type of M4 in the released dataset

### ISSUE THREAD

**Issue by Richar-Du** [Nicous20/FunQA#14]
Thanks for your awesome work! I have downloaded the dataset but find that there is no samples with task type of M4.

<img width="475" alt="image" src="https://github.com/Jingkang50/FunQA/assets/55051961/d33c0972-86d3-4f15-afaa-682ee0defd8d">

**Comment by Nicous20** [comment]
Thanks for your follow-up! In the current version of FunQA, most annotators weren't professional magicians. M4 will be released in the next version of FunQA.
